name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Check out the code from your repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Xcode
    - name: Set up Xcode
      uses: actions/setup-xcode@v3
      with:
        xcode-version: '16.1'  # Ustaw wersję Xcode, której używasz

    # Run tests
    - name: Run tests
      run: xcodebuild clean test -project "MyApp.xcodeproj" -scheme "MyApp" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

    # Build the app
    - name: Build App
      run: xcodebuild -project "MyApp.xcodeproj" -scheme "MyApp" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO