name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: |
        sudo xcode-select --install
        xcode-select -p # Wypisuje lokalizację Xcode, aby sprawdzić, czy działa

    - name: Run tests
      run: |
        xcodebuild test -scheme YourSchemeName