name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Check out the code from your repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Xcode environment and install certificates using fastlane match
    - name: Set up Xcode environment
      uses: akiojin/setup-xcode-environment-github-action@v2
      with:
        type: 'development'  # Typ certyfikatu: development, appstore, adhoc, itd.
        app-identifier: com.example.MyApp  # Zmień na identyfikator Twojej aplikacji
        team-id: ABC0123456  # Twój Team ID z Apple Developer Portal
        git-url: 'https://github.com/your-org/certificates'  # Repozytorium Git z certyfikatami
        git-passphrase: ${{ secrets.APPLE_CERTIFICATE_GIT_PASSPHASE }}  # Hasło do repozytorium

    # Run tests
    - name: Run tests
      run: xcodebuild clean test -project "MyApp.xcodeproj" -scheme "MyApp" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

    # Build the app
    - name: Build App
      run: xcodebuild -project "MyApp.xcodeproj" -scheme "MyApp" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO