name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    # Check out the code from your repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up fastlane (for managing provisioning profiles and certificates)
    - name: Install fastlane
      run: |
        brew install fastlane

    # Authenticate with GitHub to access the certificates repository
    - name: Set up Git credentials
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global credential.helper store
        echo "https://${{ secrets.GITHUB_TOKEN }}:@github.com" > ~/.git-credentials

    # Set up Xcode environment and install certificates using fastlane match
    - name: Set up Xcode environment
      uses: akiojin/setup-xcode-environment-github-action@v2
      with:
        type: 'development'  # Typ certyfikatu: development, appstore, adhoc, itd.
        app-identifier: pl.example.art2.Arkanoid2  # Twój identyfikator aplikacji
        team-id: 4H8FG658ND  # Twój Team ID z Apple Developer Portal
        git-url: 'https://github.com/Art721/certificates'  # Repozytorium Git z certyfikatami
        git-passphrase: ${{ secrets.APPLE_CERTIFICATE_GIT_PASSPHASE }}  # Hasło do repozytorium z certyfikatami

    # Run tests
    - name: Run tests
      run: xcodebuild clean test -project "Arkanoid2.xcodeproj" -scheme "Arkanoid2" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

    # Build the app
    - name: Build App
      run: xcodebuild -project "Arkanoid2.xcodeproj" -scheme "Arkanoid2" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO